### ISSUE TITLE
No such file or directory resources/emojis

### ISSUE THREAD

**Issue by divansantana** [blak3mill3r/vmd-mode#10]
Hello,

Thanks for this cool extension.

Not sure if I'm doing something wrong, using spacemacs on Arch Linux with the [markdown layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/+lang/markdown), I get this error when I try enable vmd-mode:
```
byte-code: Opening input file: No such file or directory, /home/admin/git/fnb/my-wiki/something/resources/emojis [2 times]
```
vmd-mode fails to load.

I then do something like this:
```
mkdir /home/admin/git/fnb/my-wiki/something/resources/
touch /home/admin/git/fnb/my-wiki/something/resources/emojis
```
Then I can enable vmd-mode. Shouldn't the above not be required?

**Comment by cormacc** [comment]
I see the same behaviour, similar config (Arch / spacemacs / markdown layer)

**Comment by blak3mill3r** [comment]
Thanks for reporting. It certainly should not be required. I will look into it.

**Comment by blak3mill3r** [comment]
e3b27f4f179002984643895292bb207c3e221a5c will probably fix it.

**Comment by divansantana** [comment]
@blak3mill3r it does - thanks a ton.
