### ISSUE TITLE
Under markdown layer, live preview does not work

### ISSUE THREAD

**Issue by Reapor-Yurnero** [blak3mill3r/vmd-mode#13]
When using [markdown layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/markdown#live-preview), I followed the instruction and set layer 
```
(markdown :variables markdown-live-preview-engine 'vmd-mode)
```
However, typing ```spc-m-c-P``` which should allow live preview using engine defined with layer variable ```markdown-live-preview-enginewill``` will actually leads to a safari window saying /bin/bash: markdown: command not found. 
I have already npm installed vmd and it can work properly independently. I wonder why this is not calling vmd to render the .md file and what shall I do to make it work properly.

**Comment by blak3mill3r** [comment]
Apologies for not responding to this for so long...

Unfortunately I do not have Spacemacs or `markdown layer` installed so it isn't easy for me to try to reproduce this. May I suggest that you either file an issue with `spacemacs`, or try to reproduce the issue yourself with just emacs and `vmd-mode`?

**Comment by BrandonShega** [comment]
This is super old, almost a year lol, but I think what you want is
`(markdown :variables markdown-live-preview-engine 'vmd)`
that works for me.
