### ISSUE TITLE
melpa install does not include the emojis completions

### ISSUE THREAD

**Issue by idcrook** [blak3mill3r/vmd-mode#15]
If `vmd-mode` is installed via `package-install vmd-mode`, the emoji completion list seems to be missing.

in `vmd-mode.el` saw this

```el
(defvar vmd-mode--emojis-file "./resources/emojis"
```

but the `resources/` directory seems to be missing, the ELPA install area only containing these files:

```
  -rw-r--r--   1 user staff   659 Jun 18 07:21 vmd-mode-autoloads.el
  -rw-r--r--   1 user staff   301 Jun 18 07:21 vmd-mode-pkg.el
  -rw-r--r--   1 user staff  3831 Jun 18 07:21 vmd-mode.el
  -rw-r--r--   1 user staff  5069 Jun 18 07:21 vmd-mode.elc
```

**Comment by blak3mill3r** [comment]
Workaround: I think if you call `(vmd-mode--update-emojis-file)` it will fetch them from the GH API.

**Comment by idcrook** [comment]
Thanks for the suggestion. Here's output I got when trying to run this command interactively using `*scratch*` buffer: 

```emacs-lisp
Debugger entered--Lisp error: (file-missing "Opening output file" "No such file or directory" "/Users/user/resources/emojis")
  write-region(nil nil "./resources/emojis" nil 0)
  vmd-mode--update-emojis-file()
  eval((vmd-mode--update-emojis-file) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by idcrook** [comment]
by the way, manually installing like the following did not work, I guess since '.' in the filename is wherever emacs was launched from:

```bash
cd ~/.emacs.d/elpa/vmd-mode-20180223.556
mkdir resources
cd resources/
wget https://github.com/blak3mill3r/vmd-mode/raw/master/resources/emojis
```
I tweaked `vmd-mode.el` with this:
```emacs-lisp
(defconst vmd-mode--emojis-file (expand-file-name "emojis" user-emacs-directory)
  "File containing emoji names.")
```

and then ran `(vmd-mode--update-emojis-file)` and it created the file at `~/.emacs.d/emojis` and then the `company-mode` completions started working.

**Comment by idcrook** [comment]
Thanks for the suggestion.  As a workaround I put this, which also works, in my emacs startup:

```elisp
(use-package vmd-mode
  :config
  (setq vmd-mode--emojis-file  (expand-file-name "emojis" temp-dir))
  ;;(add-hook 'markdown-mode-hook 'vmd-mode)
  ;; run this if needed (vmd-mode--update-emojis-file)
  )
```

In my config `temp-dir`, which I have defined specifically for caching things like this, is a subdirectory of `user-emacs-directory`

I'll let you decide if you would want to update anything with that, as since my config works, I won't be doing a PR for this issue.
